version: '3'

services:
  api-crowdfunding:
    image: api-crowdfunding
    build: ./
    env_file:
      - .env
    container_name: api-crowdfunding
    restart: always
    ports:
      - '4000:4000'
    depends_on:
      - mongodb

  mongodb:
    image: mongo:latest
    ports:
      - "27017:27017"
    env_file:
      - .env
    environment:
      - MONGO_INITDB_DATABASE=${DB_NAME}
    volumes:      
      - ./mongodb-data:/data/db

networks:
  default:
    name: crowdfunding
