version: '3'

services:
  mongodb:
    image: mongo:latest
    ports:
      - "27017:27017"
    env_file:
      - .env
    environment:
      - MONGO_INITDB_DATABASE=${DB_NAME}
    volumes:      
      - ./mongodb-data:/data/db

